### ISSUE TITLE
how to get a value of the spline

### ISSUE THREAD

**Issue by ev-br** [diana-sukhoverkhova/project_spline_interp#3]
There should be a function to compute a value of the spline at a given point. Since you're doing it in a class-based way, make your class callable:

```
def __call__(self, xnew):
    """Return the value of the spline at `xnew`.""""
    ....
```

then the API is similar to

```
>>> spl = cyclic_spline_curve(...)    # __init__ constructs an instance here
>>> for xnew in [0.1, 0.2, 42.]:
...    ynew = spl(xnew)
```

and then the `draw`  method can be moved out of the class into the userspace, so that the class is not coupled to matplotlib being available.

Ping me when done, I'll show an outline of how to arrange testing.

**Comment by diana-sukhoverkhova** [comment]
The problem is solved: #5

**Comment by ev-br** [comment]
Will take a look, thanks.
(Ping me again if no response by the end of the day Friday, here or in 408).

**Comment by ev-br** [comment]
A small piece of GH magic: https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#:~:text=Closing%20multiple%20issues-,About%20issue%20references,corresponding%20issue%20is%20automatically%20closed.
